name: MavenArtifactsTracker
description: Simple Flutter app to track Maven dependencies

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  scoped_model: ^1.0.0
  rxdart: ^0.20.0
  intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1
  flutter_launcher_icons: "^0.7.0"

flutter:
  uses-material-design: true
  assets:
    - assets/provider/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
